services:
  mainapp:
    build:
      context: .
      dockerfile: src/Gitcg.NetCord.MainApp/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    container_name: gitcg-netcord-mainapp