// <auto-generated />
using System;
using GitcgNetCord.MainApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitcgNetCord.MainApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250810114028_AddDiscordCardCodeChannelDataSet")]
    partial class AddDiscordCardCodeChannelDataSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitcgNetCord.MainApp.Entities.ActiveHoyolabAccount", b =>
                {
                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("HoyolabAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("DiscordUserId");

                    b.HasIndex("HoyolabAccountId");

                    b.ToTable("ActiveHoyolabAccounts");
                });

            modelBuilder.Entity("GitcgNetCord.MainApp.Entities.DiscordCardCodeChannel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("DiscordCardCodeChannels");
                });

            modelBuilder.Entity("GitcgNetCord.MainApp.Entities.DiscordUser", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("DiscordUsers");
                });

            modelBuilder.Entity("GitcgNetCord.MainApp.Entities.HoyolabAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GameRoleId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HoyolabUserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.ToTable("HoyolabAccounts");
                });

            modelBuilder.Entity("GitcgNetCord.MainApp.Entities.ActiveHoyolabAccount", b =>
                {
                    b.HasOne("GitcgNetCord.MainApp.Entities.DiscordUser", "DiscordUser")
                        .WithOne("ActiveHoyolabAccount")
                        .HasForeignKey("GitcgNetCord.MainApp.Entities.ActiveHoyolabAccount", "DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitcgNetCord.MainApp.Entities.HoyolabAccount", "HoyolabAccount")
                        .WithMany()
                        .HasForeignKey("HoyolabAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordUser");

                    b.Navigation("HoyolabAccount");
                });

            modelBuilder.Entity("GitcgNetCord.MainApp.Entities.HoyolabAccount", b =>
                {
                    b.HasOne("GitcgNetCord.MainApp.Entities.DiscordUser", "DiscordUser")
                        .WithMany("HoyolabAccounts")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordUser");
                });

            modelBuilder.Entity("GitcgNetCord.MainApp.Entities.DiscordUser", b =>
                {
                    b.Navigation("ActiveHoyolabAccount");

                    b.Navigation("HoyolabAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
